apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: job2
spec:
  max-instances: 2
  min-instances: 2
  cleanPodPolicy: "All"
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            - 'curl -s https://lsalab.cs.nthu.edu.tw/~ericyeh/DRAGON/mnist-df.py | python3 -'
            command:
            - /bin/bash
            - -c
            image: tensorflow/tensorflow:1.15.0-py3
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            "kubeshare/gpu_request": "0.5"
            "kubeshare/gpu_limit": "1.0"
            "kubeshare/gpu_mem": "3189243904" # 3G
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - args:
            - 'curl -s https://lsalab.cs.nthu.edu.tw/~ericyeh/DRAGON/mnist-df.py | python3 -'
            env:
            - name: global_steps
              value: "10000"
            command:
            - /bin/bash
            - -c
            image: tensorflow/tensorflow:1.15.0-gpu-py3
            name: tensorflow
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              requests:
                cpu: "4"
                memory: "1Gi"
